NETHER_STAR_COOLANT_CELL:
  
  # supports color codes
  Name: '&r&f&lNether Star Coolant Cell'

  # must be an ID from a research registered in researches.yml
  Research: advanced_cooling_systems

  # type can be HEAD or NORMAL
  Item:
    type: HEAD
    id: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTY5OWMxMTIxMDljMWNlYzEwODk5OTQwYTg2MDFkZWUwNTk0YzEzMDNjY2NhZmI4NTk1ODk1MmU2NzU4MjlmZiJ9fX0='
  
  # recipe for the item. n can range from 0 to 8; other entries will be ignored
  # if an item is not found, nothing will be required in that slot
  Recipe:
    type: ENHANCED_CRAFTING_TABLE
    amount: 8

    items:
      0: nether_star
  

  # lore lines; delete this section if your item does not have lore
  Lore:
  - '&7Coolant for heavy machinery'


BLACK_STAR:

  Name: '&8&lBlack Star'
  Research: advanced_cooling_systems

  Item:
    type: NORMAL
    id: 'nether_star'

  Recipe:
    type: HEATED_PRESSURE_CHAMBER
    amount: 2

    items:
      0: nether_star
      1: carbonado

  Lore:
  - '&7Specialized coolant for high-end machinery'


NIOBIUM_DUST:

  Name: '&eNiobium dust'
  Research: advanced_alloys

  Item:
    type: NORMAL
    id: 'sugar'

  Recipe:
    type: 'NULL'
    amount: 1


CHROMIUM_DUST:

  Name: '&5Chromium dust'
  Research: advanced_alloys

  Item:
    type: NORMAL
    id: 'sugar'

  Recipe:
    type: 'NULL'
    amount: 1


ZIRCONIUM_DUST:

  Name: '&5Zirconium Dust'
  Research: advanced_alloys

  Item:
    type: NORMAL
    id: 'gunpowder'

  Recipe:
    type: 'NULL'
    amount: 1


SNNBFECRNI_ALLOY:

  Name: '&eSnNbFeCrNi Alloy'
  Research: advanced_alloys

  Item:
    type: NORMAL
    id: 'iron_ingot'

  Recipe:
    type: SMELTERY
    amount: 1

    items:
      0: tin_ingot
      1: niobium_dust
      2: iron_ingot
      3: chromium_dust
      4: nickel_ingot