Description: An advanced gold pan that processes large amounts of gravel and soul sand at a high efficiency, in exchange for large amounts of power and coolant cells.
ClassName: ProcessingMachine
FuelName: "Coolant"


Fuels:
  fuel-1: '1800 black_star'
  fuel-2: '900 nether_star_coolant_cell'



Recipes:
  recipe-1:

    TIME: 20
    ENERGY: 20

    INPUT:
      item-1: '64 gravel'

    OUTPUT:
      item-1: '32 sifted_ore'
  
  
  recipe-2:
    TIME: 20
    ENERGY: 20

    INPUT:
      item-1: '64 soul_sand'

    OUTPUT:
      item-1: '2 ghast_tear'
      item-2: '4 glowstone_dust'
      item-3: '6 blaze_powder'
      item-4: '7 nether_wart'
      item-5: '7 gold_nugget'
      item-6: '32 quartz'